---
title: "Data Dictionary"
author: "Yang Lyu"
date: "11/11/2023"
output: pdf_document
---

```{r}
library(tidyverse)
library(kableExtra)
```

```{r}
BASA <- read.csv("BASA_AUC_2028_912.csv", header = TRUE)
dat_F <- read.csv("dat_F_sub.csv", header = TRUE)
dat_P <- read.csv("dat_P_sub_c.csv", header = TRUE)
years <- read.csv("years20262030.csv", header = TRUE)
```

```{r}
#create data variable definition
DataDict_BASA <- data.frame(
  Variables = colnames(BASA), 
  Data_type = sapply(BASA, function(x) class(x)),
  Example = sapply(BASA, function(x) paste(as.character(head(unique(x),2)), collapse = ", ")),
  Number_of_Missing = sapply(BASA, function(x) sum(is.na(x))),
  Meanings = c("Row numbers.",
            "The airfield where the passenger departed",
            "Recored date and time when passenger was scaned at S2",
            "The waiting time of passenger in queue from S1 to S2",
            "The number of security agents at S1 when passenger was scaned",
            "The number of security agents at S2 when passenger was scaned",
            "The average of security agents at S1 and S2",
            "Date and time of the passenger's schedule departure on the flight",
            "Date and time of the passenger's actual departure on the flight",
            "The destination city",
            "The destination country code",
            "The order of passengers",
            "Passenger ID",
            "Date of depature",
            "Time of depature(recored in seconds: h*3600+m*60+s)",
            "The time period of day when departed",
            "The period of week when departed",
            "The day of week when departed",
            "The month of departure",
            "The season of departure",
            "The year of departure"
            )
)

DataDict_BASA%>%remove_rownames()%>%kable(booktabs = TRUE,caption = "Data Dictionary of BASA")%>%
  kable_styling(font_size=10, latex_options=c("striped","scale_down","hold_position"))%>%
  column_spec(5, width = "20em")%>%
  row_spec(0,bold=TRUE)
```