---
title: "temp1_pj3"
author: "Yang Lyu"
date: "06/11/2023"
output: pdf_document
---

```{r}
library(dplyr)
library(lubridate)
```

```{r}
BASA <- read.csv("BASA_AUC_2028_912.csv", header = TRUE)
dat_F <- read.csv("dat_F_sub.csv", header = TRUE)
dat_P <- read.csv("dat_P_sub_c.csv", header = TRUE)
years <- read.csv("years20262030.csv", header = TRUE)
```

```{r}
BASA$Period_of_Week[BASA$Period_of_Week == "1 - WEEKDAY"] <- "temp"
BASA$Period_of_Week[BASA$Period_of_Week == "2 - WEEKEND"] <- "1 - WEEKDAY"
BASA$Period_of_Week[BASA$Period_of_Week == "temp"] <- "2 - WEEKEND"

BASA_WEEKDAY <- BASA %>% filter(Period_of_Week == "1 - WEEKDAY" & Day_of_Week %in% c("	
1 - MON","2 - TUE","	
3 - WED","4 - THU","	
5 - FRI"))

BASA_WEEKEND <- BASA %>% filter(Period_of_Week == "2 - WEEKEND" & Day_of_Week %in% c("6 - SAT","7 - SUN"))

BASA_WEEKDAY_SUMMER <- BASA_WEEKDAY %>% filter(Season == "3 - SUMMER")
BASA_WEEKDAY_AUTUMN <- BASA_WEEKDAY %>% filter(Season == "4 - AUTUMN")
BASA_WEEKEND_SUMMER <- BASA_WEEKEND %>% filter(Season == "3 - SUMMER")
BASA_WEEKEND_AUTUMN <- BASA_WEEKEND %>% filter(Season == "4 - AUTUMN")
```

```{r}
FilterByTimeS2 <- function(df, start_time, end_time, interval_minutes) {
  df$S2 <- as.POSIXct(df$S2)
  df$Time <- format(df$S2, "%H:%M:%S")
  result <- list()

  for (start in seq(0, 24 * 60, by = interval_minutes)) {
    end <- start + interval_minutes
    interval_start_time <- sprintf("%02d:%02d:%02d", start %/% 60, start %% 60, 0)
    interval_end_time <- sprintf("%02d:%02d:%02d", end %/% 60, end %% 60, 0)

    # Filter rows within the current time interval
    filtered_df <- df[df$Time >= interval_start_time & df$Time < interval_end_time, ]

    # Add the filtered data frame to the list
    result[[paste(interval_start_time, interval_end_time, sep = "_")]] <- filtered_df
  }

  return(result)
}
```

```{r}
# fill missing wait time with mean
fill_missing <- function(df){
  mean_value <- round(mean(df$Wait_Time, na.rm = TRUE),0)
  df$Wait_Time[is.na(df$Wait_Time)] <- mean_value
  return(df)
}
```

```{r}
List1 <- list(BASA_WEEKDAY_SUMMER,BASA_WEEKDAY_AUTUMN,BASA_WEEKEND_SUMMER,BASA_WEEKEND_AUTUMN)
```

```{r}
time_interval <- c("00:00:00_04:00:00","04:00:00_08:00:00","08:00:00_12:00:00","12:00:00_16:00:00","16:00:00_20:00:00","20:00:00_24:00:00")
BASA_fill <- data.frame()

for(i in c(1,2,3,4)){
  filter_df <- FilterByTimeS2(List1[[i]], start_time = "00:00:00", end_time = "24:00:00", 240)
  for(j in time_interval){
    filter_fill <- fill_missing(filter_df[[j]])
    BASA_fill <- rbind(BASA_fill,filter_fill)
  }
}
```

```{r}
# Ccalculate S1 = S2-Wait_Time
BASA_fill$S2 <- as.POSIXct(BASA_fill$S2, format = "%Y-%m-%d %H:%M:%S")
BASA_fill$S1 <- BASA_fill$S2 - as.numeric(BASA_fill$Wait_Time) * 60 
sum(is.na(BASA$S1))
sum(is.na(BASA$S2))
```

```{r}
FilterByTimeS1 <- function(df, start_time, end_time, interval_minutes) {
  df$S1 <- as.POSIXct(df$S1)
  df$Time <- format(df$S1, "%H:%M:%S")
  result <- list()

  for (start in seq(0, 24 * 60, by = interval_minutes)) {
    end <- start + interval_minutes
    interval_start_time <- sprintf("%02d:%02d:%02d", start %/% 60, start %% 60, 0)
    interval_end_time <- sprintf("%02d:%02d:%02d", end %/% 60, end %% 60, 0)

    # Filter rows within the current time interval
    filtered_df <- df[df$Time >= interval_start_time & df$Time < interval_end_time, ]

    # Add the filtered data frame to the list
    result[[paste(interval_start_time, interval_end_time, sep = "_")]] <- filtered_df
  }

  return(result)
}
```

```{r}
BASA_WEEKDAY <- BASA_fill %>% filter(Period_of_Week == "1 - WEEKDAY" & Day_of_Week %in% c("	
1 - MON","2 - TUE","	
3 - WED","4 - THU","	
5 - FRI"))

BASA_WEEKEND <- BASA_fill %>% filter(Period_of_Week == "2 - WEEKEND" & Day_of_Week %in% c("6 - SAT","7 - SUN"))
```

```{r}
BASA_WEEKDAY_SUMMER <- BASA_WEEKDAY %>% filter(Season == "3 - SUMMER")
BASA_WEEKDAY_AUTUMN <- BASA_WEEKDAY %>% filter(Season == "4 - AUTUMN")
BASA_WEEKEND_SUMMER <- BASA_WEEKEND %>% filter(Season == "3 - SUMMER")
BASA_WEEKEND_AUTUMN <- BASA_WEEKEND %>% filter(Season == "4 - AUTUMN")
```

```{r}
List2 <- list(BASA_WEEKDAY_SUMMER,BASA_WEEKDAY_AUTUMN,BASA_WEEKEND_SUMMER,BASA_WEEKEND_AUTUMN)
```

```{r}
Result <- data.frame()
for(i in c(1,2,3,4)){
  filter_df <- FilterByTimeS1(List2[[i]], start_time = "00:00:00", end_time = "24:00:00", 240)
  for(j in time_interval){
    if(i == 1){
      cluster <- filter_df[[j]]
      lambda <-nrow(cluster)/(13*5*4)
      Wq <-mean(cluster$Wait_Time)
      mu <- (Wq*lambda+sqrt((Wq*lambda)^2+4*Wq*lambda))/(2*Wq)
      Result <- rbind(Result,c("Summer","Weekday",j,lambda,Wq,mu))
    }
    else if(i == 2){
      cluster <- filter_df[[j]]
      lambda <- nrow(cluster)/(13*5*4)
      Wq <- mean(cluster$Wait_Time)
      mu <- (Wq*lambda+sqrt((Wq*lambda)^2+4*Wq*lambda))/(2*Wq)
      Result <- rbind(Result,c("Autumn","Weekday",j,lambda,Wq,mu))
    }
    else if(i == 3){
      cluster <- filter_df[[j]]
      lambda <- nrow(cluster)/(13*2*4)
      Wq <- mean(cluster$Wait_Time)
      mu <- (Wq*lambda+sqrt((Wq*lambda)^2+4*Wq*lambda))/(2*Wq)
      Result <- rbind(Result,c("Summer","Weekend",j,lambda,Wq,mu))
    }
    else{
      cluster <- filter_df[[j]]
      lambda <- nrow(cluster)/(13*2*4)
      Wq <- mean(cluster$Wait_Time)
      mu <- (Wq*lambda+sqrt((Wq*lambda)^2+4*Wq*lambda))/(2*Wq)
      Result <- rbind(Result,c("Autumn","Weekend",j,lambda,Wq,mu))
    }
  }
}
colnames(Result) <- c("Season","Period_of_week","Time_Period","Arrival_rate","Avg_Wait_Time","Service_rate")
View(Result)
```

```{r}
# 定义参数
lambda <- 5
  # 平均到达率 (arrivals per time unit)
mu <- 6      # 平均服务率 (services per time unit)

# 模拟时间
sim_time <- 1000

# 初始化变量
queue <- numeric(0)  # 队列
clock <- 0           # 时钟
arrivals <- 0        # 到达数
departures <- 0      # 服务完成数

# 模拟循环
while (clock < sim_time) {
  # 计算下一个到达和服务时间
  inter_arrival_time <- rexp(1, lambda)
  arrival_time <- clock + inter_arrival_time
  
  service_time <- rexp(1, mu)
  departure_time <- clock + service_time
  
  # 处理到达事件
  if (arrival_time < departure_time || departures == 0) {
    arrivals <- arrivals + 1
    queue <- c(queue, arrival_time)
    clock <- arrival_time
  } else {  # 处理服务完成事件
    departures <- departures + 1
    queue <- queue[-1]
    clock <- departure_time
  }
}
# 计算模拟结果
average_waiting_time <- sum(departure_time - queue) / departures

# 打印结果
cat("Average Waiting Time:", average_waiting_time, "\n")
cat("Total Arrivals:", arrivals, "\n")
cat("Total Departures:", departures, "\n")
```

https://www.math.pku.edu.cn/teachers/lidf/docs/statcomp/html/_statcompbook/sim-des.html
```{r}
demo.mm1 <- function(T0=0, T1=10000, lambda, mu, DEBUG=FALSE){
  ## 初始化
  t <- 0     # 时钟
  B <- FALSE # 柜员忙标志
  L <- 0     # 排队等候人数
  i <- 0     # 当前到达顾客号
  j <- 0     # 正在接受服务顾客号
  n <- 0     # 已结束服务顾客数
  max_events <- T1/lambda*2 # 设置一个较大的时间集合存储空间
  a <- numeric(max_events) # 顾客到来时间的集合
  s <- numeric(max_events) # 顾客开始服务时间的集合
  e <- numeric(max_events) # 顾客结束服务时间的集合
  X <- rexp(1, lambda); A <- X # 下一顾客到来时间
  E <- NA         # 下一个服务结束时间
  
  ## 时钟反复跳到下一事件发生的时间，并处理事件，更新待发生事件集合
  repeat{
    if(DEBUG){
      cat('\n')
      cat('t=', round(t,2), ' B=', as.integer(B), ' L=', L,
          ' i=', i, ' A=', round(A,2),
          ' n=', n, ' E=', round(E,2), 
          ' j=', j, 
          '\n', sep='')
      cat('到达序列', round(a,2), '\n')
      cat('开始序列', round(s,2), '\n')
      cat('结束序列', round(e,2), '\n')
    }
    if(!B || (B && A<E)){ # 不忙，或待处理下一到来事件
      t <- A
    } else {
      t <- E
    }
    if(t > T1) break
    
    if(t == A){ # 待处理到达事件
      L <- L+1
      i <- i+1; a[i] <- t
      X <- rexp(1, lambda); A <- t + X
      if(!B){
        B <- TRUE
        L <- L-1
        j <- j+1; s[j] <- t
        Y <- rexp(1, mu); E <- t + Y
      } # if !B
    } else { # 待处理结束服务事件
      B <- FALSE
      n <- n+1; e[n] <- t
      if(L > 0){
        L <- L-1
        B <- 1
        j <- j+1; s[j] <- t
        Y <- rexp(1, mu); E <- t + Y
      }
    } # end of 待处理结束服务事件
  } # end of repeat
  
  nn <- min(c(i, j, n))
  a <- a[seq(nn)]
  s <- s[seq(nn)]
  e <- e[seq(nn)]
  I <- a >= T0 & a <= T1
  ER <- mean(e[I] - a[I])
  ER.true <- 1/(mu-lambda)
  cat('估计的平均滞留时间ER=', ER,
      ' 期望值=', ER.true, '\n')
  c(ER.hat=ER, ER.true=ER.true)
}
```


```{r}
set.seed(1)
demo.mm1(T0=0,T1=100000, 6.55769230769231
,6.63054265619527,DEBUG=FALSE)
mean(S2_FourEight_BASA_WEEKDAY_SUMMER$Wait_Time)
mean(S1_FourEight_BASA_WEEKDAY_SUMMER$Wait_Time)
(mean(S2_FourEight_BASA_WEEKDAY_SUMMER$Wait_Time)+mean(S1_FourEight_BASA_WEEKDAY_SUMMER$Wait_Time))/2
```

```{r}
mean(S2_FourEight_BASA_WEEKDAY_SUMMER$Wait_Time)
mean(S2_EightTwelve_BASA_WEEKDAY_SUMMER$Wait_Time)
mean(S2_TwelveSixteen_BASA_WEEKDAY_SUMMER$Wait_Time)
mean(S2_SixteenTwenty_BASA_WEEKDAY_SUMMER$Wait_Time)
mean(S2_TwentyTwentyfour_BASA_WEEKDAY_SUMMER$Wait_Time)
```

```{r}
View(Result[-c(1,7,13,19),])
set.seed(1)
for(n in 1:nrow(Result[-c(1,7,13,19),])){
  demo.mm1(T0=0,T1=100000, as.numeric(Result[-c(1,7,13,19),]$Arrival_rate[n]),as.numeric(Result[-c(1,7,13,19),]$Service_rate[n]),DEBUG=FALSE)
  }
```

```{r}
# 定义参数
lambda <- 5   # 平均到达率 (arrivals per time unit)
mu <- 6       # 平均服务率 (services per time unit)
sim_time <- 10# 模拟时间

# 初始化变量
queue <- numeric(0)  # 队列
clock <- 0           # 时钟
arrivals <- 0        # 到达数
departures <- 0      # 服务完成数
waittime<-0          #等待时长

inter_arrival_time <- rexp(1, lambda)
arrival_time<- inter_arrival_time#第一个乘客到达时间
clock<-arrival_time

# 模拟循环从第二个乘客开始
while (clock < sim_time) {
  # 计算下一个到达和服务时间
  service_time <- rexp(1, mu)
  departure_time <- arrival_time + service_time
  inter_arrival_time <- rexp(1, lambda)
  arrival_time<- arrival_time + inter_arrival_time
  # 处理到达事件
  if (arrival_time < departure_time) {
    arrivals <- arrivals + 1
    clock <- arrival_time
    waittime<-departure_time-arrival_time
  } else {  # 处理服务完成事件
    arrivals<-arrivals + 1
    departures <- departures + 1
    queue <- queue-1
    waittime<-waittime
  }
}

# 计算模拟结果
average_waiting_time <- waittime / arrivals

# 打印结果
cat("Average Waiting Time:", average_waiting_time, "\n")
cat("Total Arrivals:", arrivals, "\n")
cat("Total Departures:", departures, "\n")
```


Group by season, period of week, time of day

```{r}
a <- subset(BASA,BASA$X == 284974)
a$S2
a$Time_of_Day
```

```{r}
TimeOfDay <- unique(BASA_fill$Time_of_Day)
```