---
title: "temp_pj3"
author: "Yang Lyu"
date: "06/11/2023"
output: pdf_document
---

```{r}
library(dplyr)
library(lubridate)
```

```{r}
BASA <- read.csv("BASA_AUC_2028_912.csv", header = TRUE)
dat_F <- read.csv("dat_F_sub.csv", header = TRUE)
dat_P <- read.csv("dat_P_sub_c.csv", header = TRUE)
years <- read.csv("years20262030.csv", header = TRUE)
```

```{r}
# View(BASA)
BASA_missing_percentage <- sapply(BASA, function(x) {
  sum(is.na(x)) / length(x) * 100
})

# Print the missing percentage for each column
print(BASA_missing_percentage)
```

```{r}
BASA$Period_of_Week[BASA$Period_of_Week == "1 - WEEKDAY"] <- "temp"
BASA$Period_of_Week[BASA$Period_of_Week == "2 - WEEKEND"] <- "1 - WEEKDAY"
BASA$Period_of_Week[BASA$Period_of_Week == "temp"] <- "2 - WEEKEND"

BASA_WEEKDAY <- BASA %>% filter(Period_of_Week == "1 - WEEKDAY" & Day_of_Week %in% c("	
1 - MON","2 - TUE","	
3 - WED","4 - THU","	
5 - FRI"))

BASA_WEEKEND <- BASA %>% filter(Period_of_Week == "2 - WEEKEND" & Day_of_Week %in% c("6 - SAT","7 - SUN"))
```

```{r}
BASA_WEEKDAY_SUMMER <- BASA_WEEKDAY %>% filter(Season == "3 - SUMMER")
BASA_WEEKDAY_AUTUMN <- BASA_WEEKDAY %>% filter(Season == "4 - AUTUMN")
BASA_WEEKEND_SUMMER <- BASA_WEEKEND %>% filter(Season == "3 - SUMMER")
BASA_WEEKEND_AUTUMN <- BASA_WEEKEND %>% filter(Season == "4 - AUTUMN")
```

```{r}
# View(years)
years_missing_percentage <- sapply(years, function(x) {
  sum(is.na(x)) / length(x) * 100
})

# missing percentage for each column
print(years_missing_percentage)
```

```{r}
table(years$Airfield)
```

Note that 7,8,9: Summer
          10,11,12:Autumn
          1,2,3:Winter
          
```{r}

# test if same
BASA_WEEKDAY_SUMMER$S2 <- as.POSIXct(BASA_WEEKDAY_SUMMER$S2)
BASA_WEEKDAY_SUMMER$Time <- format(BASA_WEEKDAY_SUMMER$S2, "%H:%M:%S")

# 0 to 4
ZeroFour_BASA_WEEKDAY_SUMMER <- BASA_WEEKDAY_SUMMER[BASA_WEEKDAY_SUMMER$Time >= "00:00:00" & BASA_WEEKDAY_SUMMER$Time <= "04:00:00", ]

# 4 to 8
FourEight_BASA_WEEKDAY_SUMMER <- BASA_WEEKDAY_SUMMER[BASA_WEEKDAY_SUMMER$Time >= "04:00:00" & BASA_WEEKDAY_SUMMER$Time <= "08:00:00", ]

# 8 to 12
EightTwelve_BASA_WEEKDAY_SUMMER <- BASA_WEEKDAY_SUMMER[BASA_WEEKDAY_SUMMER$Time >= "08:00:00" & BASA_WEEKDAY_SUMMER$Time <= "12:00:00", ]

# 12 to 16
TwelveSixteen_BASA_WEEKDAY_SUMMER <- BASA_WEEKDAY_SUMMER[BASA_WEEKDAY_SUMMER$Time >= "12:00:00" & BASA_WEEKDAY_SUMMER$Time <= "16:00:00", ]
```

```{r}
FilterByTimeS2 <- function(df, start_time, end_time, interval_minutes) {
  df$S2 <- as.POSIXct(df$S2)
  df$Time <- format(df$S2, "%H:%M:%S")
  result <- list()

  for (start in seq(0, 24 * 60, by = interval_minutes)) {
    end <- start + interval_minutes
    interval_start_time <- sprintf("%02d:%02d:%02d", start %/% 60, start %% 60, 0)
    interval_end_time <- sprintf("%02d:%02d:%02d", end %/% 60, end %% 60, 0)

    # Filter rows within the current time interval
    filtered_df <- df[df$Time >= interval_start_time & df$Time < interval_end_time, ]

    # Add the filtered data frame to the list
    result[[paste(interval_start_time, interval_end_time, sep = "_")]] <- filtered_df
  }

  return(result)
}
```

```{r}
# fill missing wait time with mean
fill_missing <- function(df){
  mean_value <- round(mean(df$Wait_Time, na.rm = TRUE),0)
  df$Wait_Time[is.na(df$Wait_Time)] <- mean_value
  return(df)
}
```

```{r}
# For S2, group by interval = 4 hours for BASA summer weekday
S2_BASA_SummerWeekday <- FilterByTimeS2(BASA_WEEKDAY_SUMMER, start_time = "00:00:00", end_time = "24:00:00", 240)

S2_ZeroFour_BASA_WEEKDAY_SUMMER <- fill_missing(S2_BASA_SummerWeekday[["00:00:00_04:00:00"]])
S2_FourEight_BASA_WEEKDAY_SUMMER <- fill_missing(S2_BASA_SummerWeekday[["04:00:00_08:00:00"]])
S2_EightTwelve_BASA_WEEKDAY_SUMMER <- fill_missing(S2_BASA_SummerWeekday[["08:00:00_12:00:00"]])
S2_TwelveSixteen_BASA_WEEKDAY_SUMMER <- fill_missing(S2_BASA_SummerWeekday[["12:00:00_16:00:00"]])
S2_SixteenTwenty_BASA_WEEKDAY_SUMMER <- fill_missing(S2_BASA_SummerWeekday[["16:00:00_20:00:00"]])
S2_TwentyTwentyfour_BASA_WEEKDAY_SUMMER <- fill_missing(S2_BASA_SummerWeekday[["20:00:00_24:00:00"]])
```

```{r}
nrow(S2_ZeroFour_BASA_WEEKDAY_SUMMER)
nrow(S2_FourEight_BASA_WEEKDAY_SUMMER)
```

```{r}
# group by interval = 4 hours for BASA autumn weekday
S2_BASA_AutumnWeekday <- FilterByTimeS2(BASA_WEEKDAY_AUTUMN, start_time = "00:00:00", end_time = "24:00:00", 240)

S2_ZeroFour_BASA_WEEKDAY_AUTUMN <- fill_missing(S2_BASA_AutumnWeekday[["00:00:00_04:00:00"]])
S2_FourEight_BASA_WEEKDAY_AUTUMN <- fill_missing(S2_BASA_AutumnWeekday[["04:00:00_08:00:00"]])
S2_EightTwelve_BASA_WEEKDAY_AUTUMN <- fill_missing(S2_BASA_AutumnWeekday[["08:00:00_12:00:00"]])
S2_TwelveSixteen_BASA_WEEKDAY_AUTUMN <- fill_missing(S2_BASA_AutumnWeekday[["12:00:00_16:00:00"]])
S2_SixteenTwenty_BASA_WEEKDAY_AUTUMN <- fill_missing(S2_BASA_AutumnWeekday[["16:00:00_20:00:00"]])
S2_TwentyTwentyfour_BASA_WEEKDAY_AUTUMN <- fill_missing(S2_BASA_AutumnWeekday[["20:00:00_24:00:00"]])
```

```{r}
# group by interval = 4 hours for BASA summer weekend
S2_BASA_SummerWeekend <- FilterByTimeS2(BASA_WEEKEND_SUMMER, start_time = "00:00:00", end_time = "24:00:00", 240)

S2_ZeroFour_BASA_WEEKEND_SUMMER <- fill_missing(S2_BASA_SummerWeekend[["00:00:00_04:00:00"]])
S2_FourEight_BASA_WEEKEND_SUMMER <- fill_missing(S2_BASA_SummerWeekend[["04:00:00_08:00:00"]])
S2_EightTwelve_BASA_WEEKEND_SUMMER <- fill_missing(S2_BASA_SummerWeekend[["08:00:00_12:00:00"]])
S2_TwelveSixteen_BASA_WEEKEND_SUMMER <- fill_missing(S2_BASA_SummerWeekend[["12:00:00_16:00:00"]])
S2_SixteenTwenty_BASA_WEEKEND_SUMMER <- fill_missing(S2_BASA_SummerWeekend[["16:00:00_20:00:00"]])
S2_TwentyTwentyfour_BASA_WEEKEND_SUMMER <- fill_missing(S2_BASA_SummerWeekend[["20:00:00_24:00:00"]])
```

```{r}
# group by interval = 4 hours for BASA autumn weekend
S2_BASA_AutumnWeekend <- FilterByTimeS2(BASA_WEEKEND_AUTUMN, start_time = "00:00:00", end_time = "24:00:00", 240)

S2_ZeroFour_BASA_WEEKEND_AUTUMN <- fill_missing(S2_BASA_AutumnWeekend[["00:00:00_04:00:00"]])
S2_FourEight_BASA_WEEKEND_AUTUMN <- fill_missing(S2_BASA_AutumnWeekend[["04:00:00_08:00:00"]])
S2_EightTwelve_BASA_WEEKEND_AUTUMN <- fill_missing(S2_BASA_AutumnWeekend[["08:00:00_12:00:00"]])
S2_TwelveSixteen_BASA_WEEKEND_AUTUMN <- fill_missing(S2_BASA_AutumnWeekend[["12:00:00_16:00:00"]])
S2_SixteenTwenty_BASA_WEEKEND_AUTUMN <- fill_missing(S2_BASA_AutumnWeekend[["16:00:00_20:00:00"]])
S2_TwentyTwentyfour_BASA_WEEKEND_AUTUMN <- fill_missing(S2_BASA_AutumnWeekend[["20:00:00_24:00:00"]])
```

```{r}
BASA_fill <- rbind(S2_ZeroFour_BASA_WEEKDAY_SUMMER,S2_FourEight_BASA_WEEKDAY_SUMMER,S2_EightTwelve_BASA_WEEKDAY_SUMMER,S2_TwelveSixteen_BASA_WEEKDAY_SUMMER,S2_SixteenTwenty_BASA_WEEKDAY_SUMMER,S2_TwentyTwentyfour_BASA_WEEKDAY_SUMMER,S2_ZeroFour_BASA_WEEKDAY_AUTUMN,S2_FourEight_BASA_WEEKDAY_AUTUMN,S2_EightTwelve_BASA_WEEKDAY_AUTUMN,S2_TwelveSixteen_BASA_WEEKDAY_AUTUMN,S2_SixteenTwenty_BASA_WEEKDAY_AUTUMN,S2_TwentyTwentyfour_BASA_WEEKDAY_AUTUMN,S2_ZeroFour_BASA_WEEKEND_SUMMER,S2_FourEight_BASA_WEEKEND_SUMMER,S2_EightTwelve_BASA_WEEKEND_SUMMER,S2_TwelveSixteen_BASA_WEEKEND_SUMMER,S2_SixteenTwenty_BASA_WEEKEND_SUMMER,S2_TwentyTwentyfour_BASA_WEEKEND_SUMMER,S2_ZeroFour_BASA_WEEKEND_AUTUMN,S2_FourEight_BASA_WEEKEND_AUTUMN,S2_EightTwelve_BASA_WEEKEND_AUTUMN,S2_TwelveSixteen_BASA_WEEKEND_AUTUMN,S2_SixteenTwenty_BASA_WEEKEND_AUTUMN,S2_TwentyTwentyfour_BASA_WEEKEND_AUTUMN)
```

```{r}
# Ccalculate S1 = S2-Wait_Time
BASA_fill$S2 <- as.POSIXct(BASA_fill$S2, format = "%Y-%m-%d %H:%M:%S")
BASA_fill$S1 <- BASA_fill$S2 - as.numeric(BASA_fill$Wait_Time) * 60 
sum(is.na(BASA$S1))
sum(is.na(BASA$S2))
```

```{r}
FilterByTimeS1 <- function(df, start_time, end_time, interval_minutes) {
  df$S1 <- as.POSIXct(df$S1)
  df$Time <- format(df$S1, "%H:%M:%S")
  result <- list()

  for (start in seq(0, 24 * 60, by = interval_minutes)) {
    end <- start + interval_minutes
    interval_start_time <- sprintf("%02d:%02d:%02d", start %/% 60, start %% 60, 0)
    interval_end_time <- sprintf("%02d:%02d:%02d", end %/% 60, end %% 60, 0)

    # Filter rows within the current time interval
    filtered_df <- df[df$Time >= interval_start_time & df$Time < interval_end_time, ]

    # Add the filtered data frame to the list
    result[[paste(interval_start_time, interval_end_time, sep = "_")]] <- filtered_df
  }

  return(result)
}
```

```{r}
BASA_WEEKDAY <- BASA_fill %>% filter(Period_of_Week == "1 - WEEKDAY" & Day_of_Week %in% c("	
1 - MON","2 - TUE","	
3 - WED","4 - THU","	
5 - FRI"))

BASA_WEEKEND <- BASA_fill %>% filter(Period_of_Week == "2 - WEEKEND" & Day_of_Week %in% c("6 - SAT","7 - SUN"))
```

```{r}
BASA_WEEKDAY_SUMMER <- BASA_WEEKDAY %>% filter(Season == "3 - SUMMER")
BASA_WEEKDAY_AUTUMN <- BASA_WEEKDAY %>% filter(Season == "4 - AUTUMN")
BASA_WEEKEND_SUMMER <- BASA_WEEKEND %>% filter(Season == "3 - SUMMER")
BASA_WEEKEND_AUTUMN <- BASA_WEEKEND %>% filter(Season == "4 - AUTUMN")
```

```{r}
# group by interval = 4 hours for BASA summer weekday
S1_BASA_SummerWeekday <- FilterByTimeS1(BASA_WEEKDAY_SUMMER, start_time = "00:00:00", end_time = "24:00:00", 240)

S1_ZeroFour_BASA_WEEKDAY_SUMMER <- S1_BASA_SummerWeekday[["00:00:00_04:00:00"]]
S1_FourEight_BASA_WEEKDAY_SUMMER <- S1_BASA_SummerWeekday[["04:00:00_08:00:00"]]
S1_EightTwelve_BASA_WEEKDAY_SUMMER <- S1_BASA_SummerWeekday[["08:00:00_12:00:00"]]
S1_TwelveSixteen_BASA_WEEKDAY_SUMMER <- S1_BASA_SummerWeekday[["12:00:00_16:00:00"]]
S1_SixteenTwenty_BASA_WEEKDAY_SUMMER <- S1_BASA_SummerWeekday[["16:00:00_20:00:00"]]
S1_TwentyTwentyfour_BASA_WEEKDAY_SUMMER <- S1_BASA_SummerWeekday[["20:00:00_24:00:00"]]
```

```{r}
# group by interval = 4 hours for BASA autumn weekday
S1_BASA_AutumnWeekday <- FilterByTimeS1(BASA_WEEKDAY_AUTUMN, start_time = "00:00:00", end_time = "24:00:00", 240)

S1_ZeroFour_BASA_WEEKDAY_AUTUMN <- S1_BASA_AutumnWeekday[["00:00:00_04:00:00"]]
S1_FourEight_BASA_WEEKDAY_AUTUMN <- S1_BASA_AutumnWeekday[["04:00:00_08:00:00"]]
S1_EightTwelve_BASA_WEEKDAY_AUTUMN <- S1_BASA_AutumnWeekday[["08:00:00_12:00:00"]]
S1_TwelveSixteen_BASA_WEEKDAY_AUTUMN <- S1_BASA_AutumnWeekday[["12:00:00_16:00:00"]]
S1_SixteenTwenty_BASA_WEEKDAY_AUTUMN <- S1_BASA_AutumnWeekday[["16:00:00_20:00:00"]]
S1_TwentyTwentyfour_BASA_WEEKDAY_AUTUMN <- S1_BASA_AutumnWeekday[["20:00:00_24:00:00"]]
```

```{r}
# group by interval = 4 hours for BASA summer weekend
S1_BASA_SummerWeekend <- FilterByTimeS1(BASA_WEEKEND_SUMMER, start_time = "00:00:00", end_time = "24:00:00", 240)

S1_ZeroFour_BASA_WEEKEND_SUMMER <- S1_BASA_SummerWeekend[["00:00:00_04:00:00"]]
S1_FourEight_BASA_WEEKEND_SUMMER <- S1_BASA_SummerWeekend[["04:00:00_08:00:00"]]
S1_EightTwelve_BASA_WEEKEND_SUMMER <- S1_BASA_SummerWeekend[["08:00:00_12:00:00"]]
S1_TwelveSixteen_BASA_WEEKEND_SUMMER <- S1_BASA_SummerWeekend[["12:00:00_16:00:00"]]
S1_SixteenTwenty_BASA_WEEKEND_SUMMER <- S1_BASA_SummerWeekend[["16:00:00_20:00:00"]]
S1_TwentyTwentyfour_BASA_WEEKEND_SUMMER <- S1_BASA_SummerWeekend[["20:00:00_24:00:00"]]
```

```{r}
# group by interval = 4 hours for BASA autumn weekend
S1_BASA_AutumnWeekend <- FilterByTimeS1(BASA_WEEKEND_AUTUMN, start_time = "00:00:00", end_time = "24:00:00", 240)

S1_ZeroFour_BASA_WEEKEND_AUTUMN <- S1_BASA_AutumnWeekend[["00:00:00_04:00:00"]]
S1_FourEight_BASA_WEEKEND_AUTUMN <- S1_BASA_AutumnWeekend[["04:00:00_08:00:00"]]
S1_EightTwelve_BASA_WEEKEND_AUTUMN <- S1_BASA_AutumnWeekend[["08:00:00_12:00:00"]]
S1_TwelveSixteen_BASA_WEEKEND_AUTUMN <- S1_BASA_AutumnWeekend[["12:00:00_16:00:00"]]
S1_SixteenTwenty_BASA_WEEKEND_AUTUMN <- S1_BASA_AutumnWeekend[["16:00:00_20:00:00"]]
S1_TwentyTwentyfour_BASA_WEEKEND_AUTUMN <- S1_BASA_AutumnWeekend[["20:00:00_24:00:00"]]
```
